title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://sugengdcahyo.github.com/notasiku
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: sugengdcahyo
  twitter: sugegdcahyo
  facebook: dwicahayana
  email: sugengdcahyo@gmail.com

google_analytics: "UA-58263416-1"

disqus:
    shortname: sugengdcahyo
